"""
Visualize anomaly heatmap + per-concept prototype heatmaps from trained AnomalyCLIP model.
Batch mode: process multiple images and generate summary report.

Usage:
  python visualize_heatmap.py                        # default: 100 images from BUSI
  python visualize_heatmap.py --num_images 50         # process 50 images
  python visualize_heatmap.py --image path/to/img.png # single image mode
"""
import argparse
import os
import sys
import csv
import random
from datetime import datetime
from collections import defaultdict

import torch
import torch.nn.functional as F
import numpy as np
import matplotlib
matplotlib.use("Agg")  # non-interactive backend
import matplotlib.pyplot as plt
from PIL import Image
import torchvision.transforms as transforms
import warnings
warnings.filterwarnings("ignore", category=FutureWarning)

from dassl.config import get_cfg_default
from open_clip.src.open_clip import create_model_from_pretrained

from trainers.AnomalyDetect.anomaly_detect import AnomalyCLIP
from trainers.AnomalyDetect.text_descriptions import get_text_descriptions


def extend_cfg(cfg):
    from yacs.config import CfgNode as CN
    cfg.TRAINER.BIOMEDCOOP = CN()
    cfg.TRAINER.BIOMEDCOOP.CTX_INIT = "a photo of a"
    cfg.TRAINER.BIOMEDCOOP.CSC = False
    cfg.TRAINER.BIOMEDCOOP.CLASS_TOKEN_POSITION = "end"
    cfg.TRAINER.BIOMEDCOOP.N_CTX = 4
    cfg.TRAINER.BIOMEDCOOP.PREC = "fp32"
    cfg.TRAINER.BIOMEDCOOP.SCCM_LAMBDA = 0.75
    cfg.TRAINER.BIOMEDCOOP.KDSP_LAMBDA = 0.75
    cfg.TRAINER.BIOMEDCOOP.TAU = 1.5
    cfg.TRAINER.BIOMEDCOOP.N_PROMPTS = 50
    cfg.TRAINER.ANOMALY_DETECT = CN()
    cfg.TRAINER.ANOMALY_DETECT.PREC = "fp32"
    cfg.TRAINER.ANOMALY_DETECT.LAMBDA_CONSIST = 0.5
    cfg.TRAINER.ANOMALY_DETECT.THRESHOLD_STD = 1.5
    cfg.TRAINER.ANOMALY_DETECT.PATCH_TEMPERATURE = 0.07
    cfg.OPTIM.MAX_EPOCH = 30
    cfg.DATASET.NAME = "BUSI"
    return cfg


def collect_images(dataset_dir, num_images, seed=42):
    """Collect image paths evenly distributed across classes."""
    random.seed(seed)

    classes = ["benign_tumor", "malignant_tumor", "normal_scan"]
    class_images = {}
    for cls in classes:
        cls_dir = os.path.join(dataset_dir, cls)
        if os.path.isdir(cls_dir):
            imgs = [os.path.join(cls_dir, f) for f in os.listdir(cls_dir)
                    if f.lower().endswith((".png", ".jpg", ".jpeg"))]
            random.shuffle(imgs)
            class_images[cls] = imgs
        else:
            class_images[cls] = []

    # Distribute evenly
    per_class = num_images // len(classes)
    remainder = num_images % len(classes)

    selected = []
    for i, cls in enumerate(classes):
        take = per_class + (1 if i < remainder else 0)
        take = min(take, len(class_images[cls]))
        selected.extend([(img_path, cls) for img_path in class_images[cls][:take]])

    random.shuffle(selected)
    return selected


def build_model(device, cfg, classnames):
    """Load BiomedCLIP and build AnomalyCLIP once."""
    print("Loading BiomedCLIP...")
    model, preprocess = create_model_from_pretrained(
        'hf-hub:microsoft/BiomedCLIP-PubMedBERT_256-vit_base_patch16_224'
    )
    model.float().eval()

    text_descriptions = get_text_descriptions("BUSI")

    print("Building AnomalyCLIP...")
    clip_model = AnomalyCLIP(cfg, classnames, model, text_descriptions)
    clip_model.to(device)
    clip_model.eval()

    return clip_model, preprocess


def load_checkpoint(clip_model, checkpoint_path, device):
    """Load trained weights if available, otherwise use init weights."""
    if os.path.exists(checkpoint_path):
        print(f"Loading {checkpoint_path}...")
        ckpt = torch.load(checkpoint_path, map_location=device, weights_only=False)
        state = ckpt["state_dict"]
    else:
        # Generate init checkpoint
        print(f"Checkpoint not found. Creating initial weights at {checkpoint_path}...")
        os.makedirs(os.path.dirname(checkpoint_path), exist_ok=True)
        state = clip_model.state_dict()
        ckpt = {"state_dict": state, "epoch": 0}
        torch.save(ckpt, checkpoint_path)

    # Pop token_prefix and token_suffix (regenerated by PromptLearner)
    for k in ["prompt_learner.token_prefix", "prompt_learner.token_suffix"]:
        state.pop(k, None)
    clip_model.load_state_dict(state, strict=False)
    print("Model ready.")


def process_one_image(clip_model, img_path, device, classnames):
    """Run inference on a single image. Returns (fig, concept_fig, result_dict)."""
    tfm = transforms.Compose([
        transforms.Resize(224),
        transforms.CenterCrop(224),
        transforms.ToTensor(),
        transforms.Normalize(mean=(0.48145466, 0.4578275, 0.40821073),
                             std=(0.26862954, 0.26130258, 0.27577711)),
    ])

    img = Image.open(img_path).convert("RGB")
    W, H = img.size

    inp = tfm(img).unsqueeze(0).to(device)

    with torch.no_grad():
        logits, s_img, anomaly_scores, concept_scores = clip_model(inp)

    probs = F.softmax(logits, dim=1)[0]
    pred_idx = probs.argmax().item()
    pred_class = classnames[pred_idx]
    pred_prob = probs[pred_idx].item()

    # Heatmap: [196] -> [14, 14] -> upsample
    hm_raw = anomaly_scores[0].cpu().numpy().reshape(14, 14)
    hm_big = np.array(Image.fromarray(hm_raw).resize((W, H), Image.BILINEAR))

    # Stats for heatmap
    hm_mean = float(hm_raw.mean())
    hm_max = float(hm_raw.max())
    hm_std = float(hm_raw.std())
    above_mean_pct = float((hm_raw > hm_mean).mean() * 100)

    # ── Per-concept heatmaps ──
    # Compute per-concept anomaly scores (softmax of each concept sim vs others)
    # Collect all anomaly concept scores into [14, 14, K_anom]
    anom_concept_names = list(concept_scores["anomaly"].keys())
    norm_concept_names = list(concept_scores["normal"].keys())
    K_anom = len(anom_concept_names)
    K_norm = len(norm_concept_names)

    anom_concept_maps = {}
    for cname in anom_concept_names:
        raw = concept_scores["anomaly"][cname][0].cpu().numpy().reshape(14, 14)
        anom_concept_maps[cname] = raw

    norm_concept_maps = {}
    for cname in norm_concept_names:
        raw = concept_scores["normal"][cname][0].cpu().numpy().reshape(14, 14)
        norm_concept_maps[cname] = raw

    # Find dominant concept per pixel (which anchor has highest sim)
    all_anom_sims = np.stack(list(anom_concept_maps.values()), axis=0)  # [K_anom, 14, 14]
    dominant_anom_idx = np.argmax(all_anom_sims, axis=0)  # [14, 14]
    dominant_anom_value = np.max(all_anom_sims, axis=0)   # [14, 14]

    # ── Main figure (3 panels) ──
    fig, axes = plt.subplots(1, 3, figsize=(15, 5))
    axes[0].imshow(img)
    axes[0].set_title("Original", fontsize=12)
    axes[0].axis("off")

    axes[1].imshow(img)
    im1 = axes[1].imshow(hm_big, cmap="jet", alpha=0.5, vmin=0, vmax=1)
    axes[1].set_title(f"Overlay | s_img={s_img.item():.3f}", fontsize=12)
    axes[1].axis("off")
    plt.colorbar(im1, ax=axes[1], fraction=0.046)

    axes[2].imshow(hm_raw, cmap="jet", vmin=0, vmax=1)
    axes[2].set_title(f"Raw (14x14) | Pred: {pred_class} ({pred_prob:.2%})", fontsize=12)
    axes[2].axis("off")
    plt.colorbar(im1, ax=axes[2], fraction=0.046)

    plt.tight_layout()

    # ── Per-concept figure ──
    total_concepts = K_anom + K_norm
    n_cols = min(4, total_concepts)
    n_rows = (total_concepts + n_cols - 1) // n_cols
    concept_fig, c_axes = plt.subplots(n_rows, n_cols,
                                        figsize=(4 * n_cols, 4 * n_rows))
    if n_rows == 1 and n_cols == 1:
        c_axes = np.array([[c_axes]])
    elif n_rows == 1:
        c_axes = c_axes.reshape(1, -1)
    elif n_cols == 1:
        c_axes = c_axes.reshape(-1, 1)

    concept_idx = 0
    # Anomaly concepts first
    for cname in anom_concept_names:
        r, c = concept_idx // n_cols, concept_idx % n_cols
        raw = anom_concept_maps[cname]
        # Up-sample to image size
        big = np.array(Image.fromarray(raw).resize((W, H), Image.BILINEAR))
        c_axes[r, c].imshow(img)
        c_axes[r, c].imshow(big, cmap="hot", alpha=0.6, vmin=0, vmax=1)
        c_axes[r, c].set_title(f"[ANOM] {cname}\nmax={raw.max():.3f}", fontsize=9)
        c_axes[r, c].axis("off")
        concept_idx += 1

    # Normal concepts
    for cname in norm_concept_names:
        r, c = concept_idx // n_cols, concept_idx % n_cols
        raw = norm_concept_maps[cname]
        big = np.array(Image.fromarray(raw).resize((W, H), Image.BILINEAR))
        c_axes[r, c].imshow(img)
        c_axes[r, c].imshow(big, cmap="Greens", alpha=0.5, vmin=0, vmax=1)
        c_axes[r, c].set_title(f"[NORM] {cname}\nmax={raw.max():.3f}", fontsize=9)
        c_axes[r, c].axis("off")
        concept_idx += 1

    # Hide unused subplots
    for idx in range(concept_idx, n_rows * n_cols):
        r, c = idx // n_cols, idx % n_cols
        c_axes[r, c].axis("off")

    concept_fig.suptitle(f"Per-Concept Prototype Similarity | {os.path.basename(img_path)}",
                         fontsize=11, fontweight="bold")
    concept_fig.tight_layout()

    # ── Dominant anomaly concept stats ──
    dominant_counts = {}
    for i, cname in enumerate(anom_concept_names):
        dominant_counts[cname] = float((dominant_anom_idx == i).mean())

    # Per-concept mean stats
    concept_stats = {}
    for cname in anom_concept_names:
        concept_stats[cname] = {
            "mean": float(anom_concept_maps[cname].mean()),
            "max": float(anom_concept_maps[cname].max()),
            "dominant_pct": dominant_counts.get(cname, 0.0),
            "type": "anomaly",
        }
    for cname in norm_concept_names:
        concept_stats[cname] = {
            "mean": float(norm_concept_maps[cname].mean()),
            "max": float(norm_concept_maps[cname].max()),
            "dominant_pct": 0.0,
            "type": "normal",
        }

    result = {
        "image": img_path,
        "pred_class": pred_class,
        "pred_prob": pred_prob,
        "s_img": s_img.item(),
        "hm_mean": hm_mean,
        "hm_max": hm_max,
        "hm_std": hm_std,
        "above_mean_pct": above_mean_pct,
        "dominant_anom_concept": anom_concept_names[dominant_anom_idx.mean(axis=(0, 1)).argmax()]
            if K_anom > 0 else "N/A",
        "concept_stats": concept_stats,
    }
    return fig, concept_fig, result


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--image", type=str, default=None,
                        help="Single image mode: path to image")
    parser.add_argument("--num_images", type=int, default=100,
                        help="Number of images to process in batch mode")
    parser.add_argument("--dataset_dir", type=str, default="BUSI",
                        help="Path to BUSI dataset directory")
    parser.add_argument("--checkpoint", type=str,
                        default="output/anomaly_detect/anomaly_clip/model.pth.tar-100")
    parser.add_argument("--output_dir", type=str, default="visualize_results")
    parser.add_argument("--seed", type=int, default=42)
    args = parser.parse_args()

    device = "cuda" if torch.cuda.is_available() else "cpu"
    print(f"Device: {device}")

    os.makedirs(args.output_dir, exist_ok=True)

    cfg = get_cfg_default()
    cfg = extend_cfg(cfg)
    cfg.freeze()

    classnames = ["benign_tumor", "malignant_tumor", "normal_scan"]

    # --- Build model once ---
    clip_model, _ = build_model(device, cfg, classnames)
    load_checkpoint(clip_model, args.checkpoint, device)

    # --- Single image mode ---
    if args.image:
        print(f"Single image mode: {args.image}")
        fig, concept_fig, result = process_one_image(clip_model, args.image, device, classnames)
        out_name = os.path.splitext(os.path.basename(args.image))[0]
        out_path = os.path.join(args.output_dir, f"heatmap_{out_name}.png")
        fig.savefig(out_path, dpi=150, bbox_inches="tight")
        plt.close(fig)
        concept_path = os.path.join(args.output_dir, f"concepts_{out_name}.png")
        concept_fig.savefig(concept_path, dpi=150, bbox_inches="tight")
        plt.close(concept_fig)
        print(f"Saved -> {out_path}")
        print(f"Saved -> {concept_path}")
        print(f"Prediction: {result['pred_class']} ({result['pred_prob']:.2%})")
        print(f"Anomaly score s_img: {result['s_img']:.4f}")
        print(f"Dominant anomaly concept: {result['dominant_anom_concept']}")
        return

    # --- Batch mode: process N images ---
    print(f"\n{'='*60}")
    print(f"Batch Mode: processing {args.num_images} images from {args.dataset_dir}")
    print(f"{'='*60}\n")

    image_list = collect_images(args.dataset_dir, args.num_images, seed=args.seed)
    print(f"Selected {len(image_list)} images "
          f"(benign: {sum(1 for _,c in image_list if c=='benign_tumor')}, "
          f"malignant: {sum(1 for _,c in image_list if c=='malignant_tumor')}, "
          f"normal: {sum(1 for _,c in image_list if c=='normal_scan')})\n")

    # Logging
    csv_path = os.path.join(args.output_dir, "results.csv")
    fieldnames = [
        "index", "image", "true_class", "pred_class", "pred_prob",
        "s_img", "hm_mean", "hm_max", "hm_std", "above_mean_pct",
        "dominant_anom_concept", "status"
    ]
    csv_file = open(csv_path, "w", newline="", encoding="utf-8")
    writer = csv.DictWriter(csv_file, fieldnames=fieldnames)
    writer.writeheader()

    # Per-concept summary CSV
    concept_csv_path = os.path.join(args.output_dir, "concept_stats.csv")
    concept_csv_file = open(concept_csv_path, "w", newline="", encoding="utf-8")
    concept_fieldnames = ["index", "image", "true_class", "concept_name", "type",
                          "mean_sim", "max_sim", "dominant_pct"]
    concept_writer = csv.DictWriter(concept_csv_file, fieldnames=concept_fieldnames)
    concept_writer.writeheader()

    stats = defaultdict(list)
    success = 0
    failed = 0

    for i, (img_path, true_class) in enumerate(image_list):
        try:
            fig, concept_fig, result = process_one_image(clip_model, img_path, device, classnames)

            # Save main heatmap
            img_basename = os.path.splitext(os.path.basename(img_path))[0]
            out_name = f"heatmap_{i:03d}_{true_class}_{img_basename}.png"
            out_path = os.path.join(args.output_dir, out_name)
            fig.savefig(out_path, dpi=150, bbox_inches="tight")
            plt.close(fig)

            # Save per-concept heatmap
            concept_name = f"concepts_{i:03d}_{true_class}_{img_basename}.png"
            concept_path = os.path.join(args.output_dir, concept_name)
            concept_fig.savefig(concept_path, dpi=150, bbox_inches="tight")
            plt.close(concept_fig)

            # Write main log
            row = {
                "index": i,
                "image": img_path,
                "true_class": true_class,
                "pred_class": result["pred_class"],
                "pred_prob": f"{result['pred_prob']:.4f}",
                "s_img": f"{result['s_img']:.4f}",
                "hm_mean": f"{result['hm_mean']:.4f}",
                "hm_max": f"{result['hm_max']:.4f}",
                "hm_std": f"{result['hm_std']:.4f}",
                "above_mean_pct": f"{result['above_mean_pct']:.2f}",
                "dominant_anom_concept": result.get("dominant_anom_concept", ""),
                "status": "OK",
            }
            writer.writerow(row)

            # Write per-concept stats
            for cname, cstat in result.get("concept_stats", {}).items():
                concept_writer.writerow({
                    "index": i, "image": img_path, "true_class": true_class,
                    "concept_name": cname,
                    "type": cstat.get("type", "unknown"),
                    "mean_sim": f"{cstat.get('mean', 0):.4f}",
                    "max_sim": f"{cstat.get('max', 0):.4f}",
                    "dominant_pct": f"{cstat.get('dominant_pct', 0):.4f}",
                })

            # Accumulate stats
            stats[true_class].append(result)
            success += 1
            print(f"[{i+1}/{len(image_list)}] {img_path} -> pred={result['pred_class']} "
                  f"({result['pred_prob']:.2%}) s_img={result['s_img']:.3f} "
                  f"dom={result.get('dominant_anom_concept', 'N/A')}")

        except Exception as e:
            # Record failure
            row = {k: "" for k in fieldnames}
            row.update({"index": i, "image": img_path, "true_class": true_class,
                        "status": f"FAIL: {str(e)[:100]}"})
            writer.writerow(row)
            failed += 1
            print(f"[{i+1}/{len(image_list)}] FAILED: {img_path} - {str(e)[:80]}")

    csv_file.close()
    concept_csv_file.close()

    # --- Summary Report ---
    print(f"\n{'='*60}")
    print(f"SUMMARY REPORT")
    print(f"{'='*60}")
    print(f"Total: {len(image_list)} | Success: {success} | Failed: {failed}")
    print(f"Device: {device} | Checkpoint: {args.checkpoint}")
    print(f"Results saved to: {args.output_dir}/")
    print(f"Detailed CSV: {csv_path}")
    print()

    for cls in classnames:
        if cls in stats and stats[cls]:
            vals = stats[cls]
            s_imgs = [v["s_img"] for v in vals]
            probs = [v["pred_prob"] for v in vals]
            hm_means = [v["hm_mean"] for v in vals]
            hm_maxs = [v["hm_max"] for v in vals]

            # Count predictions
            pred_counts = defaultdict(int)
            for v in vals:
                pred_counts[v["pred_class"]] += 1

            correct = pred_counts.get(cls, 0)
            total = len(vals)

            print(f"  [{cls}]  N={total} | Accuracy: {correct}/{total} = {correct/total:.1%}")
            print(f"    s_img:      mean={np.mean(s_imgs):.4f}  std={np.std(s_imgs):.4f}  "
                  f"min={np.min(s_imgs):.4f}  max={np.max(s_imgs):.4f}")
            print(f"    pred_prob:  mean={np.mean(probs):.4f}  std={np.std(probs):.4f}")
            print(f"    hm_max:     mean={np.mean(hm_maxs):.4f}  std={np.std(hm_maxs):.4f}")
            print(f"    hm_mean:    mean={np.mean(hm_means):.4f}  std={np.std(hm_means):.4f}")
            print(f"    Predictions: {dict(pred_counts)}")
            print()

    print(f"CSV log: {csv_path}")
    print(f"Outputs: {args.output_dir}/heatmap_*.png")
    print("Done.")


if __name__ == "__main__":
    main()
